### ISSUE TITLE
发布包失败

### ISSUE THREAD

**Issue by sl2782087** [cevio/cpm#4]
发布包时提示不能发布一个私有包，发现package.json中有个一private:true的属性，删除后依然提示不能发布私有包。

客户端报错
`npm notice === Tarball Details ===
npm notice name:          npmv-test
npm notice version:       2.0.0
npm notice package size:  453 B
npm notice unpacked size: 543 B
npm notice shasum:        1b73684c3fd3868de93ab9e859987c5ba041de47
npm notice integrity:     sha512-dvLQWQqrjBs4b[...]9KCuJNyMJf0vA==
npm notice total files:   3
npm notice
npm ERR! publish Failed PUT 422
npm ERR! code E422
npm ERR! you can not publish private package. : npmv-test
`   
服务端报错
`Error: you can not publish private package.
    at Object.module.exports (C:\Users\wangzy\code\my\cpm\node_modules\@clusic\catch\error.js:7:11)
    at IndexController.ForbidPublish (C:/Users/wangzy/code/my/cpm/app/controller/index.js:137:20)
    at result.push (C:\Users\wangzy\code\my\cpm\node_modules\@clusic\rex\lib\app.js:190:45)
    at dispatch (C:\Users\wangzy\code\my\cpm\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\wangzy\code\my\cpm\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\wangzy\code\my\cpm\node_modules\koa-router\lib\router.js:346:16
    at dispatch (C:\Users\wangzy\code\my\cpm\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at C:\Users\wangzy\code\my\cpm\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\wangzy\code\my\cpm\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (C:\Users\wangzy\code\my\cpm\node_modules\koa-compose\index.js:42:32)
`

**Comment by sl2782087** [comment]
好吧已经解决，包名要以@scope/name格式才能发布成功。

**Comment by cevio** [comment]
> 好吧已经解决，包名要以@scope/name格式才能发布成功。

不好意思没及时关注到。可以发布的只有全局@scope和用户体系中单独指定的user的@scope。
